#!/usr/bin/env python3
# Copyright (c) 2026 Christian Mayer and the Mundus Mirabilis contributors.
# SPDX-License-Identifier: Apache-2.0

"""rpg_os-codegen: compile a ruleset JSON schema into a strongly typed C++ header.

Usage:
  python3 codegen/rpg_os_codegen.py --ruleset rulesets/dnd5e_srd.json  --out generated/
  python3 codegen/rpg_os_codegen.py --ruleset rulesets/tde5e_core.json --out generated/

Emits ``generated/<ruleset_id>_static.hpp``. The generated code is header-only,
depends only on rpg_os/common + rpg_os/core (never on the dynamic universal
engine), still reads the ruleset JSON at runtime for the *data* database
(archetypes, ...), and is clang-format clean.

Python 3, standard library only.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

BANNER = """// Copyright (c) 2026 Christian Mayer and the Mundus Mirabilis contributors.
// SPDX-License-Identifier: Apache-2.0
//
// ============================================================================
// AUTOMATICALLY GENERATED BY RPG OS CODEGEN - DO NOT HAND EDIT
// Ruleset : {ruleset_id} ({ruleset_name})
// Source  : {source}
// Licence : {licence}
// Comment : {comment}
// ============================================================================
"""

CXX_KEYWORDS = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
    "bool", "break", "case", "catch", "char", "char8_t", "char16_t", "char32_t",
    "class", "compl", "concept", "const", "consteval", "constexpr", "constinit",
    "const_cast", "continue", "co_await", "co_return", "co_yield", "decltype",
    "default", "delete", "do", "double", "dynamic_cast", "else", "enum",
    "explicit", "export", "extern", "false", "float", "for", "friend", "goto",
    "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept",
    "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private",
    "protected", "public", "register", "reinterpret_cast", "requires", "return",
    "short", "signed", "sizeof", "static", "static_assert", "static_cast",
    "struct", "switch", "template", "this", "thread_local", "throw", "true",
    "try", "typedef", "typeid", "typename", "union", "unsigned", "using",
    "virtual", "void", "volatile", "wchar_t", "while", "xor", "xor_eq",
}


def words(text: str) -> list[str]:
    """Splits an identifier/name into alphanumeric words."""
    return [p for p in re.split(r"[^A-Za-z0-9]+", text) if p]


def camel_case(text: str) -> str:
    """Converts 'Base Attack', 'STR_mod' or 'dnd5e_attack_melee' to camelCase."""
    parts = words(text)
    if not parts:
        return "value"
    head = parts[0].lower()
    tail = "".join(p[:1].upper() + p[1:].lower() for p in parts[1:])
    name = head + tail
    if name in CXX_KEYWORDS:
        name += "_"
    return name


class FormulaTranslator:
    """Translates the restricted formula grammar to a C++ double expression.

    Identifiers are resolved via `resolve(identifier) -> C++ expression`; every
    identifier is emitted as a double so arithmetic matches the universal
    double-based evaluator exactly. `%` becomes std::fmod, `^` std::pow.
    """

    def __init__(self, resolve):
        self._resolve = resolve

    def translate(self, text: str) -> str:
        self._text = text
        self._pos = 0
        expr = self._parse_or()
        self._skip()
        if self._pos != len(self._text):
            raise ValueError(f"unexpected trailing characters in formula '{text}'")
        return expr

    # -- token helpers -----------------------------------------------------

    def _skip(self):
        while self._pos < len(self._text) and self._text[self._pos] in " \t\n":
            self._pos += 1

    def _consume(self, token: str) -> bool:
        if self._text.startswith(token, self._pos):
            self._pos += len(token)
            return True
        return False

    def _peek(self) -> str:
        return self._text[self._pos] if self._pos < len(self._text) else ""

    def _is_digit(self, c: str) -> bool:
        return c.isdigit()

    def _is_id_char(self, c: str) -> bool:
        return c.isalnum() or c in "_.'"

    # -- grammar -----------------------------------------------------------

    def _parse_or(self):
        left = self._parse_and()
        while True:
            self._skip()
            if self._consume("||"):
                left = f"({left} || {self._parse_and()})"
            else:
                return left

    def _parse_and(self):
        left = self._parse_equality()
        while True:
            self._skip()
            if self._consume("&&"):
                left = f"({left} && {self._parse_equality()})"
            else:
                return left

    def _parse_equality(self):
        left = self._parse_relational()
        while True:
            self._skip()
            if self._consume("==") or self._consume("!="):
                op = "==" if self._text[self._pos - 2 : self._pos] == "==" else "!="
                left = f"({left} {op} {self._parse_relational()})"
            else:
                return left

    def _parse_relational(self):
        left = self._parse_additive()
        while True:
            self._skip()
            for op in ("<=", ">=", "<", ">"):
                if self._consume(op):
                    left = f"({left} {op} {self._parse_additive()})"
                    break
            else:
                return left

    def _parse_additive(self):
        left = self._parse_multiplicative()
        while True:
            self._skip()
            for op in ("+", "-"):
                if self._consume(op):
                    left = f"({left} {op} {self._parse_multiplicative()})"
                    break
            else:
                return left

    def _parse_multiplicative(self):
        left = self._parse_unary()
        while True:
            self._skip()
            for op in ("*", "/", "%"):
                if self._consume(op):
                    right = self._parse_unary()
                    if op == "%":
                        left = f"std::fmod({left}, {right})"
                    else:
                        left = f"({left} {op} {right})"
                    break
            else:
                return left

    def _parse_unary(self):
        self._skip()
        if self._consume("!"):
            return f"(!{self._parse_unary()})"
        if self._consume("-"):
            return f"(-{self._parse_unary()})"
        return self._parse_power()

    def _parse_power(self):
        left = self._parse_primary()
        self._skip()
        if self._consume("^"):
            return f"std::pow({left}, {self._parse_unary()})"
        return left

    def _parse_primary(self):
        self._skip()
        if self._pos >= len(self._text):
            raise ValueError(f"unexpected end of formula '{self._text}'")
        c = self._peek()
        if c == "(":
            self._pos += 1
            expr = self._parse_or()
            self._skip()
            if not self._consume(")"):
                raise ValueError(f"missing ')' in formula '{self._text}'")
            return expr
        if c.isdigit() or c == ".":
            return self._parse_number()
        if c.isalpha() or c == "_":
            ident = self._parse_identifier()
            self._skip()
            if self._consume("("):
                args = []
                self._skip()
                if not self._consume(")"):
                    while True:
                        args.append(self._parse_or())
                        self._skip()
                        if self._consume(")"):
                            break
                        if not self._consume(","):
                            raise ValueError(f"expected ',' or ')' in '{self._text}'")
                        self._skip()
                return self._call(ident, args)
            return self._resolve(ident)
        raise ValueError(f"unexpected character '{c}' in formula '{self._text}'")

    def _parse_number(self):
        start = self._pos
        while self._pos < len(self._text) and self._is_digit(self._text[self._pos]):
            self._pos += 1
        if self._pos < len(self._text) and self._text[self._pos] == ".":
            self._pos += 1
            while self._pos < len(self._text) and self._is_digit(self._text[self._pos]):
                self._pos += 1
        if self._pos == start:
            raise ValueError(f"expected a number in formula '{self._text}'")
        raw = self._text[start : self._pos]
        if "." in raw:
            return raw
        return raw + ".0"

    def _parse_identifier(self):
        start = self._pos
        while self._pos < len(self._text) and self._is_id_char(self._text[self._pos]):
            self._pos += 1
        return self._text[start : self._pos]

    def _call(self, name: str, args: list[str]) -> str:
        fn = {
            "min": ("rpg_os::math::min", 2),
            "max": ("rpg_os::math::max", 2),
            "floor": ("rpg_os::math::floor", 1),
            "ceil": ("rpg_os::math::ceil", 1),
            "round": ("rpg_os::math::round", 1),
            "clamp": ("rpg_os::math::clamp", 3),
        }.get(name)
        if fn is None:
            raise ValueError(f"unknown function '{name}' in formula '{self._text}'")
        cpp_name, arity = fn
        if len(args) != arity:
            raise ValueError(f"{name}() expects {arity} argument(s) in '{self._text}'")
        return f"{cpp_name}({', '.join(args)})"


class Generator:
    def __init__(self, ruleset: dict):
        self.rs = ruleset
        self.attrs = ruleset.get("attributes", [])
        self.derived = ruleset.get("derived_stats", [])
        self.resources = ruleset.get("resource_pools", [])
        self.skills = ruleset.get("skills", [])
        self.checks = ruleset.get("check_types", {})
        self.cost_tables = ruleset.get("cost_tables", {})

        self.attr_members: dict[str, str] = {}
        for a in self.attrs:
            self.attr_members[a["id"]] = camel_case(a.get("name", a["id"]))
        self.derived_methods: dict[str, str] = {}
        for d in self.derived:
            self.derived_methods[d["id"]] = camel_case(d.get("name", d["id"]))
        self.skill_members: dict[str, str] = {}
        for s in self.skills:
            self.skill_members[s["id"]] = camel_case(s.get("name", s["id"]))

        # id -> C++ expression for use inside formulas (always double).
        def resolve(ident: str) -> str:
            if ident in self.attr_members:
                return f"static_cast<double>({self.attr_members[ident]})"
            if ident in self.derived_methods:
                return f"static_cast<double>({self.derived_methods[ident]}())"
            if ident in self.skill_members:
                return f"static_cast<double>({self.skill_members[ident]})"
            raise ValueError(f"unknown stat '{ident}' referenced by a formula")

        self.translator = FormulaTranslator(resolve)

    # -- members -----------------------------------------------------------

    def _resource_max_expr(self, max_stat: str) -> str:
        if max_stat in self.attr_members:
            return self.attr_members[max_stat]
        if max_stat in self.derived_methods:
            return f"{self.derived_methods[max_stat]}()"
        if max_stat in self.skill_members:
            return self.skill_members[max_stat]
        raise ValueError(f"resource max_stat '{max_stat}' is not a known stat")

    # -- generation --------------------------------------------------------

    def generate(self) -> str:
        lines: list[str] = []
        comment = self.rs.get("comment", "")
        lines.append(BANNER.format(ruleset_id=self.rs.get("ruleset_id", "ruleset"),
                                   ruleset_name=self.rs.get("ruleset_name", ""),
                                   source=self.rs.get("source", ""),
                                   licence=self.rs.get("licence", ""),
                                   comment=comment if comment else "-"))
        lines.append("#pragma once\n")
        lines.append("#include <array>")
        lines.append("#include <cstdint>")
        lines.append("#include <string>")
        lines.append("#include <string_view>")
        lines.append("#include <utility>")
        lines.append("#include <vector>")
        lines.append("")
        lines.append("#include <rpg_os/common/json.hpp>")
        lines.append("#include <rpg_os/common/types.hpp>")
        lines.append("#include <rpg_os/core/checks.hpp>")
        lines.append("#include <rpg_os/core/cost_table.hpp>")
        lines.append("#include <rpg_os/core/dice_engine.hpp>")
        lines.append("#include <rpg_os/core/math.hpp>")
        lines.append("#include <rpg_os/core/variance.hpp>")
        lines.append("")

        for ns in self._namespace_parts():
            lines.append(f"namespace {ns} {{")
        lines.append("")
        lines.extend(self._class_doc())
        lines.append("class Character {")
        lines.append("public:")
        lines.extend(self._constructor())
        lines.append("")
        lines.extend(self._attribute_members())
        lines.extend(self._skill_members_block())
        lines.extend(self._resource_members())
        lines.extend(self._derived_getters())
        lines.extend(self._get_stat())
        lines.extend(self._check_methods())
        lines.extend(self._per_skill_checks())
        lines.extend(self._cost_table_accessors())
        lines.extend(self._data_loaders())
        lines.append("};")
        lines.append("")
        for ns in reversed(self._namespace_parts()):
            lines.append(f"}} // namespace {ns}")
        return "\n".join(lines) + "\n"

    def _namespace_parts(self) -> list[str]:
        ns = self.rs.get("namespace", f"rpg_os::generated::{self.rs.get('ruleset_id', 'x')}")
        return [p for p in ns.split("::") if p]

    def _class_doc(self) -> list[str]:
        name = self.rs.get("ruleset_name", "")
        return [f"/// Strongly typed character for the {name} ruleset. Attributes",
                "/// and skills are named members; derived stats are named getters with",
                "/// compiled formulas; checks are named methods over the shared",
                "/// templates. The data database is still read from the ruleset JSON."]

    def _constructor(self) -> list[str]:
        inits = [
            f"{self._member(r['id'], r.get('name'))}({self._resource_max_expr(r['max_stat'])})"
            for r in self.resources
        ]
        if not inits:
            return ["  /// Default-constructs a character with base values."]
        return ["  /// Default-constructs a character; resources start at their maximum.",
                "  Character() : " + ", ".join(inits) + " {}"]

    def _member(self, sid: str, name: str | None) -> str:
        return camel_case(name if name else sid)

    def _attribute_members(self) -> list[str]:
        lines = ["  // ---- core attributes ----"]
        for a in self.attrs:
            if a["id"] in ("proficiency_bonus", "level", "HitPoints_Max", "Armor_Rating"):
                continue
            member = self.attr_members[a["id"]]
            lines.append(f"  int32_t {member}{{ {a.get('default', 10)} }};  // {a['id']} {a.get('name', '')}")
        extras = [a for a in self.attrs if a["id"] in ("proficiency_bonus", "level", "HitPoints_Max", "Armor_Rating")]
        if extras:
            lines.append("")
            lines.append("  // ---- other base stats ----")
            for a in extras:
                member = self.attr_members[a["id"]]
                lines.append(f"  int32_t {member}{{ {a.get('default', 0)} }};  // {a['id']} {a.get('name', '')}")
        return lines

    def _skill_members_block(self) -> list[str]:
        if not self.skills:
            return []
        lines = ["", "  // ---- skill ratings ----"]
        for s in self.skills:
            lines.append(f"  int32_t {self.skill_members[s['id']]}{{ {s.get('default', 0)} }};  // {s['id']} ({s.get('name', '')})")
        return lines

    def _resource_members(self) -> list[str]:
        lines = ["", "  // ---- resources ----"]
        for r in self.resources:
            lines.append(f"  int32_t {self._member(r['id'], r.get('name'))}{{ 0 }};  // {r['id']} (max: {r['max_stat']})")
        return lines

    def _derived_getters(self) -> list[str]:
        lines = ["", "  // ---- derived stats (compiled formulas) ----"]
        for d in self.derived:
            method = self.derived_methods[d["id"]]
            expr = self.translator.translate(d["formula"])
            lines.append(f"  [[nodiscard]] int32_t {method}() const noexcept {{")
            lines.append(f"    return static_cast<int32_t>({expr});")
            lines.append(f"  }}  // {d['id']}: {d['formula']}")
        return lines

    def _get_stat(self) -> list[str]:
        lines = ["", "  // ---- StatProvider (string -> member switch, no allocations) ----",
                 "  [[nodiscard]] int32_t getStat(std::string_view id) const noexcept {"]
        for a in self.attrs:
            lines.append(f"    if (id == \"{a['id']}\") return {self.attr_members[a['id']]};")
        for s in self.skills:
            lines.append(f"    if (id == \"{s['id']}\") return {self.skill_members[s['id']]};")
        for d in self.derived:
            lines.append(f"    if (id == \"{d['id']}\") return {self.derived_methods[d['id']]}();")
        lines.append("    return 0;")
        lines.append("  }")
        return lines

    def _check_methods(self) -> list[str]:
        lines = ["", "  // ---- named checks (from check_types) ----"]
        for cid, cfg in self.checks.items():
            method = camel_case(cid)
            kind = cfg["kind"]
            if kind == "additive_d20":
                bonus = cfg.get("bonus_stats", [])
                arr = ", ".join(f'"{b}"' for b in bonus)
                n = len(bonus)
                lines.append(f"  /// Additive d20 check '{cid}'.")
                lines.append("  template <rpg_os::StatProvider Target, rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const Target& target, "
                             "const rpg_os::CheckParams& params, Rng& rng) const {")
                if n:
                    lines.append(f"    const std::array<std::string_view, {n}> bonus{{{arr}}};")
                    lines.append(f'    return rpg_os::resolveAdditiveD20(*this, target, "{cfg.get("dice_expression", "1d20")}", bonus, "{cfg.get("target_stat", "")}", params, rng);')
                else:
                    lines.append(f'    const std::array<std::string_view, 0> bonus{{}};')
                    lines.append(f'    return rpg_os::resolveAdditiveD20(*this, target, "{cfg.get("dice_expression", "1d20")}", bonus, "{cfg.get("target_stat", "")}", params, rng);')
                lines.append("  }")
            elif kind == "roll_under_d20":
                attr = cfg["attributes"][0]
                confirm = "true" if cfg.get("confirmation_roll", False) else "false"
                lines.append(f"  /// Roll-under d20 attribute check '{cid}'.")
                lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const rpg_os::CheckParams& params, Rng& rng) const {{")
                lines.append(f'    return rpg_os::resolveRollUnderD20(*this, "{attr}", {confirm}, params, rng);')
                lines.append("  }")
            elif kind == "triple_roll_under_pool":
                attrs = cfg["attributes"]
                pool = cfg["pool_stat"]
                lines.append(f"  /// 3d20 talent check '{cid}'.")
                lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const rpg_os::CheckParams& params, Rng& rng) const {{")
                lines.append(f'    return rpg_os::resolveTripleRollUnderPool(*this, "{attrs[0]}", "{attrs[1]}", "{attrs[2]}", "{pool}", params, rng);')
                lines.append("  }")
            elif kind == "attack_vs_defense":
                lines.append(f"  /// Attack vs. defense check '{cid}'.")
                lines.append("  template <rpg_os::StatProvider Target, rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const Target& target, "
                             "const rpg_os::CheckParams& params, Rng& rng) const {")
                lines.append(f'    return rpg_os::resolveAttackVsDefense(*this, target, "{cfg["attack_stat"]}", "{cfg["parry_stat"]}", params, rng);')
                lines.append("  }")
            elif kind == "roll_under_d100":
                attr = cfg["attributes"][0]
                lines.append(f"  /// Percentile roll-under check '{cid}' (BRP).")
                lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const rpg_os::CheckParams& params, Rng& rng) const {{")
                lines.append(f'    return rpg_os::resolveRollUnderD100(*this, "{attr}", params, rng);')
                lines.append("  }")
            elif kind == "opposed_roll_under_d100":
                lines.append(f"  /// Opposed percentile contest check '{cid}' (BRP).")
                lines.append("  template <rpg_os::StatProvider Target, rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const Target& target, "
                             "const rpg_os::CheckParams& params, Rng& rng) const {")
                lines.append(f'    return rpg_os::resolveOpposedRollUnderD100(*this, target, "{cfg["attack_stat"]}", "{cfg["parry_stat"]}", params, rng);')
                lines.append("  }")
            elif kind == "resistance_roll":
                lines.append(f"  /// BRP resistance roll '{cid}'.")
                lines.append("  template <rpg_os::StatProvider Target, rpg_os::RandomNumberGenerator Rng>")
                lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const Target& target, "
                             "const rpg_os::CheckParams& params, Rng& rng) const {")
                lines.append(f'    return rpg_os::resolveResistanceRoll(*this, target, "{cfg["attack_stat"]}", "{cfg["parry_stat"]}", params, rng);')
                lines.append("  }")
            else:
                raise ValueError(f"unknown check kind '{kind}' in check type '{cid}'")
            lines.append("")
        return lines

    def _per_skill_checks(self) -> list[str]:
        if not self.skills:
            return []
        lines = ["  // ---- per-skill talent checks (TDE: each skill has its own attributes) ----"]
        for s in self.skills:
            if len(s.get("attributes", [])) != 3:
                continue
            method = "check" + camel_case(s["name"] if s.get("name") else s["id"])[:1].upper() + \
                     camel_case(s["name"] if s.get("name") else s["id"])[1:]
            attrs = s["attributes"]
            lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
            lines.append(f"  [[nodiscard]] rpg_os::CheckResult {method}(const rpg_os::CheckParams& params, Rng& rng) const {{")
            lines.append(f'    return rpg_os::resolveTripleRollUnderPool(*this, "{attrs[0]}", "{attrs[1]}", "{attrs[2]}", "{s["id"]}", params, rng);')
            lines.append("  }")
        return lines

    def _cost_table_accessors(self) -> list[str]:
        lines = ["", "  // ---- cost / progression tables ----"]
        for tid, tbl in self.cost_tables.items():
            method = camel_case(tid)
            kind = "CostTable::Kind::Threshold" if tbl["type"] == "threshold" else "CostTable::Kind::Multiplier"
            entries = []
            if "thresholds" in tbl:
                for e in tbl["thresholds"]:
                    entries.append(f"{{ {e['key']}, {e['value']} }}")
            elif "values" in tbl:
                for k, v in tbl["values"].items():
                    entries.append(f"{{ {k}, {v} }}")
            body = ", ".join(entries)
            lines.append(f"  /// Cost table '{tid}'.")
            lines.append(f"  static const rpg_os::CostTable& {method}() {{")
            lines.append(f"    static const rpg_os::CostTable table = rpg_os::CostTable::fromEntries(")
            lines.append(f"        {kind}, {tbl.get('base_factor', 1.0)}, {{{body}}});")
            lines.append("    return table;")
            lines.append("  }")
        return lines

    def _data_loaders(self) -> list[str]:
        lines = ["", "  // ---- data loading (the ruleset JSON is still read at runtime) ----",
                 "  /// Populates this character from a ruleset data record (archetype);",
                 "  /// ranged values are picked at random.",
                 "  void fromJson(const rpg_os::Json& record) {",
                 "    rpg_os::DefaultRandom rng;",
                 "    fromJson(record, rpg_os::Variance::Random, rng);",
                 "  }",
                 "",
                 "  /// As above, but picks ranged values according to `variance` (weakest,",
                 "  /// weak, average, strong, strongest) with the caller-supplied RNG.",
                 "  template <rpg_os::RandomNumberGenerator Rng>",
                 "  void fromJson(const rpg_os::Json& record, rpg_os::Variance variance, Rng& rng) {"]
        if self.attrs:
            lines.append("    if (record.contains(\"attributes\")) {")
            lines.append("      for (const auto& [key, value] : record.at(\"attributes\").items()) {")
            for a in self.attrs:
                lines.append(f"        if (key == \"{a['id']}\") {{ {self.attr_members[a['id']]} = rpg_os::readVariantValue(value, variance, rng); }}")
            lines.append("      }")
            lines.append("    }")
        if self.skills:
            lines.append("    if (record.contains(\"skills\")) {")
            lines.append("      for (const auto& [key, value] : record.at(\"skills\").items()) {")
            for s in self.skills:
                lines.append(f"        if (key == \"{s['id']}\") {{ {self.skill_members[s['id']]} = rpg_os::readVariantValue(value, variance, rng); }}")
            lines.append("      }")
            lines.append("    }")
        # refresh resources to their maximum, then honour explicit overrides
        for r in self.resources:
            member = self._member(r["id"], r.get("name"))
            lines.append(f"    {member} = {self._resource_max_expr(r['max_stat'])};")
        if self.resources:
            lines.append("    if (record.contains(\"resources\")) {")
            lines.append("      for (const auto& [key, value] : record.at(\"resources\").items()) {")
            for r in self.resources:
                lines.append(f"        if (key == \"{r['id']}\") {{ {self._member(r['id'], r.get('name'))} = rpg_os::readVariantValue(value, variance, rng); }}")
            lines.append("      }")
            lines.append("    }")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads a single archetype by id; throws std::invalid_argument when missing.")
        lines.append("  static Character fromArchetype(const rpg_os::Json& rulesetJson, std::string_view id) {")
        lines.append("    rpg_os::DefaultRandom rng;")
        lines.append("    return fromArchetype(rulesetJson, id, rpg_os::Variance::Random, rng);")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads a single archetype by id, picking ranged values per `variance`.")
        lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
        lines.append("  static Character fromArchetype(const rpg_os::Json& rulesetJson, std::string_view id,")
        lines.append("                                rpg_os::Variance variance, Rng& rng) {")
        lines.append("    for (const auto& record : rulesetJson.at(\"data\").at(\"archetypes\")) {")
        lines.append("      if (record.value(\"id\", \"\") == id) {")
        lines.append("        Character character;")
        lines.append("        character.fromJson(record, variance, rng);")
        lines.append("        return character;")
        lines.append("      }")
        lines.append("    }")
        lines.append("    throw std::invalid_argument(\"unknown archetype '\" + std::string(id) + \"'\");")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads every archetype record from the ruleset JSON's data section.")
        lines.append("  static std::vector<Character> loadArchetypes(const rpg_os::Json& rulesetJson) {")
        lines.append("    rpg_os::DefaultRandom rng;")
        lines.append("    return loadArchetypes(rulesetJson, rpg_os::Variance::Random, rng);")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads every archetype record, picking ranged values per `variance`.")
        lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
        lines.append("  static std::vector<Character> loadArchetypes(const rpg_os::Json& rulesetJson,")
        lines.append("                                                 rpg_os::Variance variance, Rng& rng) {")
        lines.append("    std::vector<Character> out;")
        lines.append("    for (const auto& record : rulesetJson.at(\"data\").at(\"archetypes\")) {")
        lines.append("      Character character;")
        lines.append("      character.fromJson(record, variance, rng);")
        lines.append("      out.push_back(std::move(character));")
        lines.append("    }")
        lines.append("    return out;")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads a single creature from data.creatures by id; throws")
        lines.append("  /// std::invalid_argument when missing (ranged values at random).")
        lines.append("  static Character fromCreature(const rpg_os::Json& rulesetJson, std::string_view id) {")
        lines.append("    rpg_os::DefaultRandom rng;")
        lines.append("    return fromCreature(rulesetJson, id, rpg_os::Variance::Random, rng);")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads a single creature by id, picking ranged values per `variance`.")
        lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
        lines.append("  static Character fromCreature(const rpg_os::Json& rulesetJson, std::string_view id,")
        lines.append("                                rpg_os::Variance variance, Rng& rng) {")
        lines.append("    for (const auto& record : rulesetJson.at(\"data\").at(\"creatures\")) {")
        lines.append("      if (record.value(\"id\", \"\") == id) {")
        lines.append("        Character character;")
        lines.append("        character.fromJson(record, variance, rng);")
        lines.append("        return character;")
        lines.append("      }")
        lines.append("    }")
        lines.append("    throw std::invalid_argument(\"unknown creature '\" + std::string(id) + \"'\");")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads every creature record from the ruleset JSON's data section.")
        lines.append("  static std::vector<Character> loadCreatures(const rpg_os::Json& rulesetJson) {")
        lines.append("    rpg_os::DefaultRandom rng;")
        lines.append("    return loadCreatures(rulesetJson, rpg_os::Variance::Random, rng);")
        lines.append("  }")
        lines.append("")
        lines.append("  /// Loads every creature record, picking ranged values per `variance`.")
        lines.append("  template <rpg_os::RandomNumberGenerator Rng>")
        lines.append("  static std::vector<Character> loadCreatures(const rpg_os::Json& rulesetJson,")
        lines.append("                                               rpg_os::Variance variance, Rng& rng) {")
        lines.append("    std::vector<Character> out;")
        lines.append("    for (const auto& record : rulesetJson.at(\"data\").at(\"creatures\")) {")
        lines.append("      Character character;")
        lines.append("      character.fromJson(record, variance, rng);")
        lines.append("      out.push_back(std::move(character));")
        lines.append("    }")
        lines.append("    return out;")
        lines.append("  }")
        return lines


def generate(ruleset: dict) -> str:
    return Generator(ruleset).generate()


def main() -> int:
    parser = argparse.ArgumentParser(description="RPG OS code generator")
    parser.add_argument("--ruleset", required=True, help="path to the ruleset JSON")
    parser.add_argument("--out", required=True, help="output directory")
    args = parser.parse_args()

    ruleset_path = pathlib.Path(args.ruleset)
    ruleset = json.loads(ruleset_path.read_text(encoding="utf-8"))
    header = generate(ruleset)

    ruleset_id = ruleset["ruleset_id"]
    out_dir = pathlib.Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{ruleset_id}_static.hpp"
    out_file.write_text(header, encoding="utf-8")
    print(f"wrote {out_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
